name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print reading
        run: echo "hello world"
      - name: print good bye
        run: echo "bye bye"
      - name: print multiline comments
        run: |
              echo "one"
              echo "two"
              echo "three"
    
      
    
